### ISSUE TITLE
Nov 3 Punch list (2)

### ISSUE THREAD

**Issue by RadhikaPPatel** [buildly-release-management/buildly-react-template#192]
- [x] In Kanban view all “issues” from GitHub should be in the card or "feature" that created it, as an Issue Icon with +X  issues that are open and associated with that card.  When that Icon is clicked on we should get a pop-up window of those cards and status.

- [x] Each card (feature) and Issue should have a link back to the GitHub or Trello card if available.

- [X] And can we use a rich text wyswig editor in the large text fields that allow us to drag and drop images into an issues in Buildly.

- [x] Cannot join Buildly org. Remove organization name auto-complete.

- [x] Comments do not save or display from what I can see... and there should be a ticker (1,2,3,4 comments) once they have been saved.

**Comment by RadhikaPPatel** [comment]
@glind How do we want the related issues to look like in the popup window? Tabular view or just plain card like view with name and description?

**Comment by glind** [comment]
> @glind How do we want the related issues to look like in the popup window? Tabular view or just plain card like view with name and description?

I think for Tabular view they just be listed underneath the parent feature, maybe with a card like outline around them and color coded very lightly based on priority of the feature.  It's possible we just just do something very similar for now because Ivy is working on the UI.UX redesign and will start implementing it soon in the Product section.

The Kanban view should be similar, like described in the first punchlist item but default to collapsed inside the feature.
